### ISSUE TITLE
Add connectable flag

### ISSUE THREAD

**Issue by fr500** [RobLoach/libretro-netplay-registry#16]
And check if the port is open from the server

PR: https://github.com/RobLoach/libretro-netplay-registry/pull/24

**Comment by RobLoach** [comment]
Do you know what the server responds with when we reach out to it? What should we send and expect as a response?

**Comment by fr500** [comment]
Not sure, just opening the port should be enough.
The idea would be to poll from the lobby server every 60 seconds or whatever instead of re-announcing

**Comment by fr500** [comment]
http://resources.infosecinstitute.com/php-build-your-own-mini-port-scanner-2/

**Comment by RobLoach** [comment]
https://github.com/RobLoach/libretro-netplay-registry/pull/24
