### ISSUE TITLE
Random usernames if no username is posted

### ISSUE THREAD

**Issue by fr500** [RobLoach/libretro-netplay-registry#23]
All the other fields should be mandatory but having a nick shouldn't, maybe we can have some kind of random names?

http://jimpix.co.uk/words/random-username-generator.asp#results

**Comment by RobLoach** [comment]
[Random Name Generator](https://github.com/nubs/random-name-generator) would be a fun option...

1. Video game names like Kamikaze Bubblegum Warrior
2. Alliterative Names like Misty Meerkat

@fr500 One requirement would be running [`composer install`](https://getcomposer.org/) on the server. Would you be able to do that?
